[package]
name = "zengine"
version = "0.1.0"
authors = ["wartyz <zwenderk@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gl = "0.14.0"
sdl2 = {version="0.34.2"}
auto_ops = "0.1.0"
image = "0.23.6"
